spring.application.name=fx-core

server.port=8085

# Enable Java 21 Virtual Threads
spring.threads.virtual.enabled=true

# FX Configuration
fx.default-spread=0.0005
fx.anchor-currency=USD

# Logging
logging.level.com.byteentropy.fx=DEBUG